name: Daily Commit

on:
  schedule:
    # Runs every day at 07:23 UTC (adjust as needed)
    - cron: "23 7 * * *"

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add commit for 23f3003751@ds.study.iitm.ac.in
        run: |
          echo "Daily run at $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit from GitHub Actions"
          git push
